# Generated by Django 5.1.4 on 2024-12-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_democontactlist_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='democontactlist',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='democontactlist',
            name='last_Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='democontactlist',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='democontactlist',
            name='role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
