# Generated by Django 5.1.4 on 2024-12-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_democontactlist_delete_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democontactlist',
            name='first_Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
